name: Test suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-all-platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            label: linux-x86
          - os: ubuntu-24.04-arm
            label: linux-arm
          - os: windows-latest
            label: windows-x86
          - os: macos-latest
            label: macos-arm

    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.label }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: v0.50.1
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

      - name: Run tests
        run: pixi run test
